# Workflow that builds, tests and then pushes the OpenHands and runtime docker images to the ghcr.io repository
name: Docker

# Always run on "main"
# Always run on tags
# For PRs, only run if explicitly triggered by the PR validation workflow
# Can also be triggered manually
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_run:
    workflows: ["PR Validation"]
    types:
      - completed
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: ''

# If triggered by a PR, it will be in the same group. However, each commit on main will be in its own unique group
concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

env:
  RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  define-matrix:
    runs-on: blacksmith
    outputs:
      base_image: ${{ steps.define-base-images.outputs.base_image }}
    steps:
      - name: Define base images
        shell: bash
        id: define-base-images
        run: |
          # Only build nikolaik on PRs, otherwise build both nikolaik and ubuntu.
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            json=$(jq -n -c '[
                { image: "nikolaik/python-nodejs:python3.12-nodejs22", tag: "nikolaik" }
              ]')
          else
            json=$(jq -n -c '[
                { image: "nikolaik/python-nodejs:python3.12-nodejs22", tag: "nikolaik" },
                { image: "ubuntu:24.04", tag: "ubuntu" }
              ]')
          fi
          echo "base_image=$json" >> "$GITHUB_OUTPUT"

  # Check if PR validation workflow succeeded
  check-prerequisites:
    name: Check PR Validation Status
    runs-on: blacksmith-4vcpu-ubuntu-2204
    if: github.event_name == 'workflow_run'
    steps:
      - name: Check PR Validation Workflow Status
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "PR Validation workflow did not succeed. Skipping Docker build."
          exit 1

  # Builds the OpenHands Docker images
  ghcr_build_app:
    name: Build App Image
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: [define-matrix, check-prerequisites]
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        base_image: ${{ fromJson(needs.define-matrix.outputs.base_image) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/all-hands-dev/openhands
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base_image.image }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/all-hands-dev/openhands:${{ matrix.base_image.tag }}-${{ env.RELEVANT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Builds the OpenHands runtime Docker images
  ghcr_build_runtime:
    name: Build Runtime Image
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: [ghcr_build_app]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/all-hands-dev/openhands-runtime
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./runtime
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/all-hands-dev/openhands-runtime:${{ env.RELEVANT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
