# Workflow that runs lint on the frontend and python code
name: Lint

# The jobs in this workflow are required, so they must run at all times
# Always run on "main"
# Always run on PRs
on:
  push:
    branches:
    - main
  pull_request:

# If triggered by a PR, it will be in the same group. However, each commit on main will be in its own unique group
concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  # Call the reusable lint workflow
  lint:
    uses: ./.github/workflows/lint-reusable.yml
    with:
      lint-python: true
      lint-frontend: true

  # Check version consistency across documentation
  check-version-consistency:
    name: Check version consistency
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: useblacksmith/setup-python@v6
        with:
          python-version: 3.12
      - name: Run version consistency check
        run: .github/scripts/check_version_consistency.py
